# Generated by Django 4.2.13 on 2026-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100)),
                ('tipo_espacio', models.CharField(choices=[('sala', 'Sala de Juntas'), ('escritorio', 'Escritorio Compartido')], max_length=20)),
                ('capacidad_personas', models.PositiveIntegerField()),
                ('piso_edificio', models.PositiveIntegerField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiene_aire', models.BooleanField(default=False)),
                ('tiene_proyector', models.BooleanField(default=False)),
                ('estado_disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
            },
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.IntegerField()),
                ('tipo_servicio', models.CharField(choices=[('cafe', 'Café'), ('internet', 'Internet Dedicado')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solicitud_especial', models.TextField(blank=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('estado_servicio', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
    ]
