# Generated by Django 6.0.6 on 2026-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('identificacion_fiscal', models.CharField(max_length=50)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('correo_corporativo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_facturacion', models.CharField(max_length=150)),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('historial_reportes', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
